### ISSUE TITLE
vital-signs-form

### ISSUE THREAD

**Issue by Ancentus** [Ancentus/dawapal-ePCR-frontend#3]
Form Title: Vital Signs
Capture the following in the form. The field name is in curly  braces.
**_edit: omit fields with asteriks_**
1. Date/Time Vital Signs Taken {vital_dateTime}
**2. Cardiac Rhythm / Electrocardiography (ECG) {vital_ecg}
**3. ECG Type {vital_ecg_type}
**4. Method of ECG Interpretation {vital_ecg_method}
5. SBP (Systolic Blood Pressure) {vital_sbp}
6. DBP (Diastolic Blood Pressure) {vital_dbp}
7. Mean Arterial Pressure {vital_mean_ap}
8. Heart Rate {vital_heart_rate}
9. Method of Heart Rate Measurement { vital_heart_rate_method}
    options: auscultated, palpated, electronic monitor
10. Pulse Oximetry {vital_pulse_oximetry}
11. Pulse Rhythm {vital_pulse_rhythm}
12. Respiratory Rate {vital_respiratory_rate}
13. Respiratory Effort {vital_respiratory_effort}
14. End Title Carbon Dioxide (ETCO2) {vital_etco2}
15. Carbon Monoxide (CO) {vital_co}
16. Blood Glucose Level {vital_blood_glucose}
17. Temperature {vital_temperature}
18. Pain Scale Score {vital_pain_scale_score}
19. Pain Scale Type {vital_pain_scale_type}
20. Stroke Scale Score {vital_stroke_scale_score}
21. Stroke Scale Type {vital_stroke_scale_type}
22.  Glasgow Coma Score-Eye {vital_coma_score_eye}
23. Glasgow Coma Score-Verbal {vital_coma_score_verbal}
24. Glasgow Coma Score-Motor {vital_coma_score_motor}
25. Glasgow Coma Score-Qualifier {vital_coma_score_qualifier}
26. Total Glasgow Coma Score {vital_coma_score_total}
27.  Reperfusion Checklist {vital_reperfusion_checklist}
28. APGAR {vital_apgar}
29. Revised Trauma Score {vital_revised_trauma-score}
30. Estimated Body Weight in Kilograms {vital_body_weight}

**Comment by Ancentus** [comment]
The following are not part of vital signs: please omit them.
Cardiac Rhythm / Electrocardiography (ECG) {vital_ecg}
ECG Type {vital_ecg_type}
Method of ECG Interpretation {vital_ecg_method}

**Comment by Edwin574** [comment]
Done with basic UI ready for using the API endpoint

**Comment by Ancentus** [comment]
How can I test this? When I run with npm start I get a blank page

**Comment by Edwin574** [comment]
You have to do 'npm install' then 'npm start'

**Comment by Ancentus** [comment]
My bad I was testing on the wrong branch! It's all good.
